export const foodUrls = [
  "./src/image/food/apple.png",
  "./src/image/food/banana.png",
  "./src/image/food/beer.png",
  "./src/image/food/burger.png",
  "./src/image/food/cake.png",
  "./src/image/food/cherry.png",
  "./src/image/food/corn.png",
  "./src/image/food/croissant.png",
  "./src/image/food/custard.png",
  "./src/image/food/dango.png",
  "./src/image/food/donut.png",
  "./src/image/food/fries.png",
  "./src/image/food/grapes.png",
  "./src/image/food/ice_cream.png",
  "./src/image/food/lemon.png",
  "./src/image/food/meat.png",
  "./src/image/food/orange.png",
  "./src/image/food/peach.png",
  "./src/image/food/pear.png",
  "./src/image/food/pie.png",
  "./src/image/food/pineapple.png",
  "./src/image/food/pisha.png",
  "./src/image/food/ramen.png",
  "./src/image/food/shaved_ice.png",
  "./src/image/food/spaghetti.png",
  "./src/image/food/strawberry.png",
  "./src/image/food/sushi.png",
  "./src/image/food/sweet_potato.png",
];

export const gameResultImgUrls = {
  miss: [
    "./src/image/cat/missOne.png",
    "./src/image/cat/missTwo.png",
    "./src/image/cat/missThree.png",
  ],
  pass: [
    "./src/image/cat/passOne.png",
    "./src/image/cat/passTwo.png",
    "./src/image/cat/passThree.png",
    "./src/image/cat/passFour.png",
    "./src/image/cat/passFive.png",
  ],
  win: ["./src/image/cat/winner.png"],
  lose: ["./src/image/cat/lose.png"],
};

export const positionArray = [
  [73, 46],
  [73 + 47, 46],
  [73 + 47 * 2, 46],
  [73 + 47 * 3, 46],
  [73 + 47 * 4, 46],
  [73 + 47 * 5, 46],
  [73 + 47 * 6, 46],
  [73 + 310, 46],
];
