export const foodUrls = [
  "./image/food/apple.png",
  "./image/food/banana.png",
  "./image/food/beer.png",
  "./image/food/burger.png",
  "./image/food/cake.png",
  "./image/food/cherry.png",
  "./image/food/corn.png",
  "./image/food/croissant.png",
  "./image/food/custard.png",
  "./image/food/dango.png",
  "./image/food/donut.png",
  "./image/food/fries.png",
  "./image/food/grapes.png",
  "./image/food/ice_cream.png",
  "./image/food/lemon.png",
  "./image/food/meat.png",
  "./image/food/orange.png",
  "./image/food/peach.png",
  "./image/food/pear.png",
  "./image/food/pie.png",
  "./image/food/pineapple.png",
  "./image/food/pisha.png",
  "./image/food/ramen.png",
  "./image/food/shaved_ice.png",
  "./image/food/spaghetti.png",
  "./image/food/strawberry.png",
  "./image/food/sushi.png",
  "./image/food/sweet_potato.png",
];

export const gameResultImgUrls = {
  miss: [
    "./image/cat/miss.jpeg",
    "./image/cat/missTwo.jpg",
    "./image/cat/loseCat.jpeg",
  ],
  pass: [
    "./image/cat/passOne.jpeg",
    "./image/cat/passTwo.jpeg",
    "./image/cat/passThree.jpeg",
    "./image/cat/passFour.png",
  ],
  win: ["./image/cat/winner.png"],
  lose: ["./image/cat/lostCat.jpeg"],
};

export const positionSetArray = [
  [
    [-28, -25],
    [+55, +30],
    [-50, +60],
    [+30, -65],
    [+60, -40],
    [+15, +75],
    [-75, +2],
    [-37, -75],
    [+95, -30],
    [-100, -80],
    [+100, +70],
    [+80, -100],
    [-50, +100],
    [-110, +50],
    [-10, -110],
  ],

  [
    [-48, -55],
    [+57, +20],
    [-30, +60],
    [+35, -35],
    [-14, -30],
    [+19, +55],
    [-50, +2],
    [+67, -75],
    [+95, -30],
    [-100, -80],
    [+70, +80],
    [+10, -90],
    [-80, +30],
    [-10, +100],
    [+110, +30],
  ],
  [
    [-8, -35],
    [+57, +20],
    [-30, +60],
    [+35, -40],
    [-44, +18],
    [+19, +65],
    [-80, +45],
    [+67, -90],
    [+95, -30],
    [-60, -90],
    [+73, +90],
    [-40, -60],
    [-70, +85],
    [-10, +100],
    [+110, +30],
  ],
];
